// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class EaalogintestTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void eaalogintest() {
    driver.Navigate().GoToUrl("http://eaapp.somee.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1550, 830);
    driver.FindElement(By.Id("loginLink")).Click();
    driver.FindElement(By.Id("UserName")).Click();
    driver.FindElement(By.Id("UserName")).SendKeys("admin");
    driver.FindElement(By.Id("Password")).SendKeys("password");
    driver.FindElement(By.Id("loginIn")).Click();
    driver.FindElement(By.LinkText("Employee List")).Click();
  }
}
